### ISSUE TITLE
您好！请教一下，我把您的项目改成垂直翻页出现了问题，请看详情

### ISSUE THREAD

**Issue by ijoncc** [hanhailong/GridPagerSnapHelper#1]
![04b6ff5e-8fd7-4b63-a8aa-8c54f1b725fe](https://user-images.githubusercontent.com/13847079/33926993-60720656-e01b-11e7-8732-6d1c17e40922.png)
![b48d343a-2841-4904-b223-b35e02551c70](https://user-images.githubusercontent.com/13847079/33927002-6c05403c-e01b-11e7-912c-a3f2dcdeeba5.png)

问题：
往下翻页是正常的，但是往上翻页就不能正常运行了

**Comment by hanhailong** [comment]
@chunca  谢谢使用，这个竖直方向我确实没有验证，这两天解决这个问题

**Comment by hanhailong** [comment]
@chunca  已经解决了
